#!/bin/sh
#
# Initialize Alicorn Docker environment with secure random password
# Copyright (c) 2025 Robert E. Lee <robert@unicornscan.org>
#
# Usage: ./scripts/docker-init.sh
#
# This script creates a .env file with a randomly generated PostgreSQL
# password for use with docker-compose.full.yml

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
ENV_FILE="${PROJECT_DIR}/.env"

# Generate a random 32-character password
generate_password() {
    # Use base64-safe characters only
    if [ -r /dev/urandom ]; then
        tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32
    else
        # Fallback for systems without /dev/urandom
        date +%s%N | sha256sum | head -c 32
    fi
}

# Main
main() {
    # Check if .env already exists
    if [ -f "${ENV_FILE}" ]; then
        echo "Configuration file already exists: ${ENV_FILE}"
        echo ""
        read -p "Regenerate with new password? [y/N] " -n 1 -r REPLY
        echo ""
        if [ "$REPLY" != "y" ] && [ "$REPLY" != "Y" ]; then
            echo "Keeping existing configuration."
            exit 0
        fi
    fi

    PASSWORD=$(generate_password)

    # Create .env file
    cat > "${ENV_FILE}" << EOF
# Alicorn Full Stack Docker Configuration
# Generated by docker-init.sh on $(date -Iseconds)
#
# IMPORTANT: This file contains your database password.
# Keep it secure and do not commit to version control.

# =============================================================================
# PostgreSQL Configuration
# =============================================================================
POSTGRES_USER=alicorn
POSTGRES_PASSWORD=${PASSWORD}
POSTGRES_DB=unicornscan

# =============================================================================
# App Settings
# =============================================================================
VITE_APP_TITLE=Alicorn
VITE_DEBUG=false
EOF

    chmod 600 "${ENV_FILE}"

    echo ""
    echo "========================================"
    echo "  Alicorn Docker Environment Initialized"
    echo "========================================"
    echo ""
    echo "Configuration saved to: ${ENV_FILE}"
    echo ""
    echo "PostgreSQL Password: ${PASSWORD}"
    echo ""
    echo "To start the full stack:"
    echo "  cd ${PROJECT_DIR}"
    echo "  docker compose -f docker-compose.full.yml up -d"
    echo ""
    echo "Web UI will be available at: http://localhost:8080"
    echo ""

    # If the unicornscan password file location is accessible, show how to sync
    UNICORN_CONF="/etc/unicornscan"
    if [ -d "${UNICORN_CONF}" ] && [ -w "${UNICORN_CONF}" ]; then
        echo "To sync with unicornscan, update modules.conf:"
        echo "  sed -i 's/password=[^;]*/password=${PASSWORD}/' ${UNICORN_CONF}/modules.conf"
        echo ""
    fi
}

main
